### ISSUE TITLE
Implement integration for tracking subsystem

### ISSUE THREAD

**Issue by Benczus** [ZsoltToth/ilona-tracking#1]
The tracking subsystem should be able to use the same measurement interface (messaging gateway) as the positioning subsystem, and should also contain an interface to the methods of the positioning subsystem.

 - [x] create zoneQuery gateway interface
 - [x] create annotation configuration for the listZones() and  getZoneByID(zoneID) methods
- [x] create positionQuery gateway interface
- [x] create annotation configuration for the getLocation(measurement) and setPositioningAlgorithm(algorithm) methods
